apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: taiga-async-rabbitmq-data  
  name: taiga-async-rabbitmq-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
