apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: taiga-db-data  
  name: taiga-db-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
