apiVersion: v1
kind: ConfigMap
metadata:
  name: variables-env  
data:
  ENABLE_TELEMETRY: "True"
  POSTGRES_DB: "taiga"
  POSTGRES_HOST: "taiga-db"
  POSTGRES_PASSWORD: "taiga"
  POSTGRES_USER: "taiga"
  RABBITMQ_DEFAULT_PASS: "taiga"
  RABBITMQ_DEFAULT_USER: "taiga"
  RABBITMQ_DEFAULT_VHOST: "taiga"
  RABBITMQ_ERLANG_COOKIE: "secret-erlang-cookie"
  RABBITMQ_PASS: "taiga"
  RABBITMQ_USER: "taiga"
  TAIGA_SECRET_KEY: "taiga-back-secret-key"
  SECRET_KEY: "taiga-back-secret-key"
  # REPLACE BY YOUR OWN DOMAIN  
  TAIGA_SITES_DOMAIN: "taiga6-dev.domain.local"
  TAIGA_SITES_SCHEME: "https"
  TAIGA_URL: "https://taiga6-dev.domain.local"
  TAIGA_WEBSOCKETS_URL: "ws://taiga6-dev.domain.local"
